[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
dimensions = { columns = 90, lines = 28 }

[font]
size = 14.0

[font.normal]
family = "Hack"
style = "Regular"

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[scrolling]
history = 10000
